### ISSUE TITLE
Lua Error nil value on default mod

### ISSUE THREAD

**Issue by caffe23** [Calinou/carbone-ng#4]
On a fresh install of minetest from (https://github.com/minetest/minetest/releases/download/0.4.12/minetest-0.4.12-win32-msvc.zip)
when i create a new world, i get the following error:
<code>
22:13:43: ERROR[main]: ========== ERROR FROM LUA ===========
22:13:43: ERROR[main]: Failed to load and run script from 
22:13:43: ERROR[main]: F:\local\minetest_carboneng\bin..\games\carbone-ng\mods\default\init.lua:
22:13:43: ERROR[main]: ...carboneng\bin..\games\carbone-ng\mods\default/nodes.lua:1687: attempt to call a nil value
22:13:43: ERROR[main]: stack traceback:
22:13:43: ERROR[main]:  ...carboneng\bin..\games\carbone-ng\mods\default/nodes.lua:1687: in main chunk
22:13:43: ERROR[main]:  [C]: in function 'dofile'
22:13:43: ERROR[main]:  ..._carboneng\bin..\games\carbone-ng\mods\default\init.lua:39: in main chunk
22:13:43: ERROR[main]: ======= END OF ERROR FROM LUA ========
</code>

**Comment by Calinou** [comment]
You need a development build of Minetest, Carbone NG is based on a minetest_game more recent than 0.4.12. This will be solved when 0.4.13 will be released.
